spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
  datasource:
    url: jdbc:h2:mem:testDB
    driverClassName: org.h2.Driver
    username: sa
    database-platform: org.hibernate.dialect.H2Dialect
