name: Sonar cloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/cache
      - name: Build app
        uses: ./.github/actions/build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test and QA Analysis
        uses: ./.github/actions/test
